package io.primer.android.events

enum class CheckoutEventType {
    TOKENIZE_SUCCESS,
    TOKENIZE_ERROR,
    TOKEN_ADDED_TO_VAULT,
    RESUME_SUCCESS,
    RESUME_ERR0R,
    EXIT,
    API_ERROR,
    SHOW_ERROR,
    TOGGLE_LOADING,
    SHOW_SUCCESS,
    DISMISS_INTERNAL,
    TOKEN_SELECTED,
    START_3DS,
    START_ASYNC_REDIRECT_FLOW,
    START_ASYNC_FLOW,
    ON_CLIENT_SESSION_ACTIONS,
    CONFIGURATION_SUCCESS,
    TOKENIZE_STARTED,
    PREPARATION_STARTED,
    PAYMENT_METHOD_PRESENTED
}
