buildscript {
    repositories { jcenter() }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
        classpath "org.koin:koin-gradle-plugin:$koin_version"
    }
}

plugins {
    id 'com.android.library'
    id 'com.kezong.fat-aar'
}

apply plugin: 'koin'
apply plugin: 'kotlin-android'
apply plugin: 'kotlinx-serialization'

ext {
    userOrganisation = 'primer-api'

    bintrayRepo = 'android'
    bintrayName = 'io.primer.android'

    publishedGroupId = 'io.primer.android'
    libraryName = 'android'
    artifact = 'android'

    libraryDescription = 'Primer SDK for Android'

    siteUrl = 'https://github.com/primer-io/primer-sdk-android'
    gitUrl = 'https://github.com/primer-io/primer-sdk-android.git'

    libraryVersion = '1.0.0-beta.10'

    developerId = 'primer-api'
    developerName = 'Primer Developers'
    developerEmail = 'developers@primerapi.com'

    licenseName = 'MIT'
    licenseUrl = 'https://tldrlegal.com/license/mit-license#fulltext'
    allLicenses = ["MIT"]
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }

    buildTypes.each {
        it.buildConfigField 'String', 'SDK_VERSION_STRING', "\"$libraryVersion\""
        it.resValue 'string', 'SDK_VERSION_STRING', libraryVersion
    }

    lintOptions {
        abortOnError false
    }
}

fataar {
    /**
     * If transitive is true, local jar module and remote library's dependencies will be embed.
     * If transitive is false, just embed first level dependency
     * Local aar project does not support transitive, always embed first level
     * Default value is false
     * @since 1.3.0
     */
    transitive = false
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.2.0'

    embed('org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.1')
    embed('org.jetbrains.kotlinx:kotlinx-serialization-core:1.0.1') {
        transitive = false
    }

    embed "org.koin:koin-core:$koin_version"
    implementation "org.koin:koin-androidx-scope:$koin_version"

    implementation 'com.google.android.material:material:1.2.1'
//    embed('com.google.android.material:material:1.2.1') {
//        transitive = false
//    }
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    embed "com.squareup.okhttp3:okhttp:3.12.1"
//    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    embed('androidx.constraintlayout:constraintlayout:2.0.4') {
        transitive = false
    }
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.2.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0'
    implementation 'androidx.fragment:fragment-ktx:1.2.5'
    implementation "androidx.core:core-ktx:1.3.2"

    embed('net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent:3.0.0-RC2') {
        //
    }
    embed('com.hbb20:ccp:2.4.5') {
        //exclude(group:'com.facebook.soloader', module:'soloader')
        transitive = false
    }

    testImplementation 'junit:junit:4.+'

    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

repositories {
    google()
    jcenter()
    mavenCentral()
    maven {
        url "https://kotlin.bintray.com/kotlinx"
    }
}

subprojects {
    tasks.withType(Javadoc).all { enabled = false }
}

apply from: 'publish.gradle'
