package io.primer.android.payment

internal const val PAYMENT_CARD_TYPE = "PAYMENT_CARD"
internal const val PAYPAL_BILLING_AGREEMENT_TYPE = "PAYPAL_BILLING_AGREEMENT"
internal const val KLARNA_CUSTOMER_TOKEN_TYPE = "KLARNA_CUSTOMER_TOKEN"
internal const val GOCARDLESS_MANDATE_TYPE = "GOCARDLESS_MANDATE"
